FROM centos:7

USER root

RUN yum clean all; \
    rpm --rebuilddb; \
    yum install -y curl which tar sudo openssh-server openssh-clients rsync

RUN yum -y update
RUN yum update -y libselinux
RUN yum -y install rpm-build
RUN yum install -y initscripts && yum clean all

# pam
RUN yum-builddep -y pam
RUN yumdownloader --source pam

RUN ssh-keygen -q -N "" -t dsa -f /etc/ssh/ssh_host_dsa_key
RUN ssh-keygen -q -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key
RUN ssh-keygen -q -N "" -t rsa -f /root/.ssh/id_rsa
RUN cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys

# Java 1.8
RUN curl -v -j -k -L -O -H 'Cookie: oraclelicense=accept-securebackup-cookie' http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.rpm
RUN rpm -i jdk-8u161-linux-x64.rpm
RUN rm -f jdk-8u161-linux-x64.rpm

ENV JAVA_HOME /usr/java/default
ENV PATH $PATH:$JAVA_HOME/bin
RUN rm -f /usr/bin/java && ln -s $JAVA_HOME/bin/java /usr/bin/java

# Hadoop 3.0.0
RUN curl -v -j -k -L -O 'http://apache.claz.org/hadoop/common/hadoop-3.0.0/hadoop-3.0.0.tar.gz'
RUN tar -xzf hadoop-3.0.0.tar.gz
RUN cp -R hadoop-3.0.0 /usr/local
RUN rm -rf hadoop-3.0.0
RUN rm -f hadoop-3.0.0
RUN cd /usr/local && ln -s ./hadoop-3.0.0 /usr/local/hadoop

RUN mkdir /usr/local/hadoop/hdfs
RUN mkdir /usr/local/hadoop/hdfs/name
RUN mkdir /usr/local/hadoop/hdfs/data

ENV HADOOP_HOME /usr/local/hadoop
ENV HADOOP_COMMON_HOME /usr/local/hadoop
ENV HADOOP_HDFS_HOME /usr/local/hadoop
ENV HADOOP_MAPRED_HOME /usr/local/hadoop
ENV HADOOP_YARN_HOME /usr/local/hadoop
ENV HADOOP_CONF_DIR /usr/local/hadoop/etc/hadoop
ENV YARN_CONF_DIR /usr/local/hadoop/etc/hadoop

ENV HDFS_NAMENODE_USER root
ENV HDFS_DATANODE_USER root
ENV HDFS_SECONDARYNAMENODE_USER root
ENV YARN_NODEMANAGER_USER root
ENV YARN_RESOURCEMANAGER_USER root

COPY ./core-site.xml /usr/local/hadoop/etc/hadoop/core-site.xml
COPY ./hdfs-site.xml /usr/local/hadoop/etc/hadoop/hdfs-site.xml

RUN $HADOOP_HOME/bin/hdfs namenode -format

COPY ssh_config /root/.ssh/config
RUN chmod 600 /root/.ssh/config
RUN chown root:root /root/.ssh/config

RUN sed  -i "/^[^#]*UsePAM/ s/.*/#&/"  /etc/ssh/sshd_config
RUN echo "UsePAM no" >> /etc/ssh/sshd_config
RUN echo "Port 2122" >> /etc/ssh/sshd_config

RUN sed -i 's/# export JAVA_HOME=/export JAVA_HOME=\/usr\/java\/default/' /usr/local/hadoop/etc/hadoop/hadoop-env.sh

# HDFS Ports
EXPOSE 50010 50020 50070 50090 8020 9000
# Map/Reduce Ports
EXPOSE 10020 19888
# Yarn Ports 
EXPOSE 8030 8031 8032 8033 8040 8042 8088
# Other ports
EXPOSE 49707 2122