filebeat:
  prospectors:
    -
      paths:
        - /usr/local/hadoop/logs/*.log
      type: log
      tags: ["hdfs-master", "log"]
    -
      paths:
        - /usr/local/hadoop/logs/*.out
      type: log
      tags: ["hdfs-master", "out"]
    -
      paths:
        - /usr/local/hadoop/logs/*.err
      type: log
      tags: ["hdfs-master", "err"]


output:
  logstash:
    hosts: ["logstash:5044"]