version: "3.2"
services:

  # Splunk Enterprise
  splunk:
    image: "splunk/splunk:7.2"
    hostname: splunk
    ports:
      - 31000:8000
    networks:
      - hadoop
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_USER=root
      - SPLUNK_PASSWORD=securepassword

  # Hadoop HDFS Master node
  hdfsmaster:
    build: 
      context: ../nbaTrends-hadoop/docker
    command: ["master"]
    hostname: hdfsmaster
    ports:
      - 50070:50070
    networks:
      - hadoop
    depends_on:
      - splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_USER=root
      - SPLUNK_PASSWORD=securepassword

  # Hadoop HDFS Worker node
  hadoopworker:
    build: 
      context: ../nbaTrends-hadoop
      dockerfile: ./docker/Dockerfile
    command: ["worker"]
    depends_on:
      - hdfsmaster
      - splunk
    networks:
      - hadoop
    deploy:
      mode: replicated
      replicas: 2
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_USER=root
      - SPLUNK_PASSWORD=securepassword

  # Spark Master Node
  sparkmaster:
    build:
      context: ../nbaTrends-jobs
      dockerfile: ./docker/Dockerfile
    command: ['master']
    hostname: sparkmaster
    ports: 
      - 30000:8080
    networks:
      - hadoop
    depends_on:
      - splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_USER=root
      - SPLUNK_PASSWORD=securepassword

  # Spark Worker Node
  sparkworker:
    build:
      context: ../nbaTrends-jobs
      dockerfile: ./docker/Dockerfile
    command: ['worker']
    depends_on: 
      - sparkmaster
      - splunk
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - hadoop
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_USER=root
      - SPLUNK_PASSWORD=securepassword

  # PySpark Jobs 
  jobs:
    build:
      context: ../nbaTrends-jobs/docker
    command: ['jobs']
    depends_on:
      - sparkmaster
      - hdfsmaster
      - splunk
    networks:
      - hadoop
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_USER=root
      - SPLUNK_PASSWORD=securepassword
      

# Network Configs
networks:
  hadoop:
    external:
      name: hadoop