version: "3.2"
services:
  elasticsearch:
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    hostname: elasticsearch
    ports:
      - 9200:9200
      - 9002:9002
      - 9003:9003
    networks:
      - elasticsearch
    deploy:
      mode: replicated
      replicas: 1

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.2
    hostname: kibana
    ports:
      - 57000:5601
    networks:
      - elasticsearch
      - hadoop
    depends_on:
      - elasticsearch
    deploy:
      mode: replicated
      replicas: 1 

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.2
    hostname: logstash
    volumes:
      - type: bind
        source: ./logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5000:5000
      - 5044:5044
    networks:
      - elasticsearch
      - hadoop
    depends_on:
      - elasticsearch
    deploy:
      mode: replicated
      replicas: 1

  hadoop_master:
    build: 
      context: ../nbaTrends-hadoop/docker
    command: ["master"]
    hostname: hdfs-master
    ports:
      - 9870:9870
    depends_on:
      - logstash
      - kibana
    networks:
      - hadoop
      - elasticsearch

networks:
  elasticsearch:
    external:
      name: elasticsearch
  hadoop:
    external:
      name: hadoop