version "3"
services:

  #
  # ELK Stack
  #
  # build elasticsearch first 
  elasticsearch:
    environment: 
      - ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    ports:
      - 9002:9002
      - 9003:9003
    networks:
      - elasticsearch
    deploy:
      mode: replicated
      replicas: 1

  # build kibana once elasticsearch is done
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.2
    ports:
      - 5601:5601
    networks:
      - elasticsearch
    depends_on:
      - elasticsearch
    deploy:
      mode: replicated
      replicas: 1

  # build logstash after kibana
  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.2
    ports:
      - 5000:5000
    networks:
      - elasticsearch
    depends_on:
      - elasticsearch
    deploy:
      mode: replicated
      replicas: 1


  #
  # Hadoop HDFS System
  #
  # build hadoop master node first
  hadoop_master:
    environment:
      - HADOOP_VERSION
    build:
      context: ../nbaTrends-hadoop/docker
      dockerfile: Dockerfile-master
    container_name: namenode
    hostname: namenode
    networks:
      - hadoop
    deploy:
      mode: replicated
      replicas: 1
  
  # create worker nodes once master is built
  hadoop_worker:
    environment:
      - HADOOP_VERSION
    build:
      context: ../nbaTrends-hadoop/docker
      dockerfile: Dockerfile-worker
    container_name: worker
    hostname: worker
    networks:
      - hadoop
    depends_on:
      - hadoop_master
    deploy:
      mode: replicated
      replicas: 3


  #
  # NBA Trends Jobs 
  #
  # Build master node first
  spark_master:
    environment:
      - SPARK_VERSION
    build:
      context: ../nbaTrends-jobs/docker
      dockerfile: Dockerfile-master
    network:
      - hadoop
      - spark
    depends_on:
      - hadoop_master
      - hadoop_worker
    deploy:
      mode: replicated
      replicas: 1

  # build spark worker nodes 
  spark_worker:
    environment:
      - SPARK_VERSION
    build:
      context: ../nbaTrends-jobs/docker
      dockerfile: Dockerfile-worker
    network:
      - hadoop
      - spark
    depends_on:
      - spark_master
    deploy:
      mode: replicated
      replicas: 3


# connectivity networks
networks:
  elasticsearch:
  hadoop:
  spark: