FROM docker.elastic.co/beats/filebeat:6.2.2

USER root

RUN yum clean all; \
    rpm --rebuilddb; \
    yum install -y curl which tar sudo openssh-server openssh-clients rsync

RUN yum -y update
RUN yum update -y libselinux

RUN ssh-keygen -q -N "" -t dsa -f /etc/ssh/ssh_host_dsa_key
RUN ssh-keygen -q -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key
RUN ssh-keygen -q -N "" -t rsa -f /root/.ssh/id_rsa
RUN cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys

# Crontab 
RUN yum install -y cronie

# Java 1.8
RUN curl -LO 'http://download.oracle.com/otn-pub/java/jdk/8u161-b12/jdk-8u161-linux-x64.rpm' -H 'Cookie: oraclelicense=accept-securebackup-cookie'
RUN rpm -i jdk-8u161-linux-x64.rpm
RUN rm jdk-8u161-linux-x64.rpm

ENV JAVA_HOME /usr/java/default
ENV PATH $PATH:$JAVA_HOME/bin
RUN rm /usr/bin/java && ln -s $JAVA_HOME/bin/java /usr/bin/java

# Spark 


RUN mkdir /root/scripts
COPY ./entrypoint-master.sh /root/scripts/entrypoint.sh

# src files for nbaTrends App
RUN mkdir /root/nbaTrends
COPY ./src/* /root/nbaTrends

ENTRYPOINT ["/root/scripts/entrypoint.sh"]