FROM docker.elastic.co/beats/filebeat:6.2.2

USER root

RUN yum clean all; \
    rpm --rebuilddb; \
    yum install -y curl which tar sudo openssh-server openssh-clients rsync

RUN yum -y update
RUN yum update -y libselinux
RUN yum install -y wget

RUN ssh-keygen -q -N "" -t dsa -f /etc/ssh/ssh_host_dsa_key
RUN ssh-keygen -q -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key
RUN ssh-keygen -q -N "" -t rsa -f /root/.ssh/id_rsa
RUN cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys

# Crontab 
RUN yum install -y cronie

# Java 1.8
RUN curl -v -j -k -L -O -H 'Cookie: oraclelicense=accept-securebackup-cookie' http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.rpm
RUN rpm -i jdk-8u161-linux-x64.rpm
RUN rm -f jdk-8u161-linux-x64.rpm

ENV JAVA_HOME /usr/java/default
ENV PATH $PATH:$JAVA_HOME/bin
RUN rm /usr/bin/java && ln -s $JAVA_HOME/bin/java /usr/bin/java

# Spark 
RUN curl -v -j -k -L -O 'http://apache.claz.org/spark/spark-2.3.0/spark-2.3.0-bin-hadoop2.7.tgz'
RUN tar -xzf spark-2.3.0-bin-hadoop2.7.tgz
RUN cp -R spark-2.3.0-bin-hadoop2.7 /usr/local
RUN rm -rf spark-2.3.0-bin-hadoop2.7
RUN rm -f spark-2.3.0-bin-hadoop2.7.tgz
RUN cd /usr/local && ln -s ./spark-2.3.0-bin-hadoop2.7 /usr/local/spark


RUN mkdir /root/scripts
COPY ./entrypoint-master.sh /root/scripts/entrypoint.sh

# src files for nbaTrends App
RUN mkdir /root/nbaTrends
COPY ./src/* /root/nbaTrends

# copy filebeat config
COPY ./filebeat-master.yml /usr/share/filebeat/filebeat.yml
RUN chown root:filebeat /usr/share/filebeat/filebeat.yml

ENTRYPOINT ["/root/scripts/entrypoint.sh"]