FROM docker.elastic.co/beats/filebeat:6.2.2

USER root

RUN yum clean all; \
    rpm --rebuilddb; \
    yum install -y curl which tar sudo openssh-server openssh-clients rsync

RUN yum -y update

RUN yum -y install yum-utils
RUN yum -y install https://$(rpm -E '%{?centos:centos}%{!?centos:rhel}%{rhel}').iuscommunity.org/ius-release.rpm

RUN ssh-keygen -q -N "" -t dsa -f /etc/ssh/ssh_host_dsa_key
RUN ssh-keygen -q -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key
RUN ssh-keygen -q -N "" -t rsa -f /root/.ssh/id_rsa
RUN cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys

# Python 3
RUN yum -y install python36u
RUN yum -y install python36u-pip
RUN pip3.6 install virtualenv

# Crontab 
RUN yum -y install cronie

# Java 1.8
RUN curl -v -j -k -L -O -H 'Cookie: oraclelicense=accept-securebackup-cookie' http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.rpm
RUN rpm -i jdk-8u161-linux-x64.rpm
RUN rm -f jdk-8u161-linux-x64.rpm

ENV JAVA_HOME /usr/java/default
ENV PATH $PATH:$JAVA_HOME/bin
RUN rm /usr/bin/java && ln -s $JAVA_HOME/bin/java /usr/bin/java

# Spark 2.3 / Hadoop 2.7
RUN curl -v -j -k -L -O 'http://apache.claz.org/spark/spark-2.3.0/spark-2.3.0-bin-hadoop2.7.tgz'
RUN tar -xzf spark-2.3.0-bin-hadoop2.7.tgz
RUN cp -R spark-2.3.0-bin-hadoop2.7 /usr/local
RUN rm -rf spark-2.3.0-bin-hadoop2.7
RUN rm -f spark-2.3.0-bin-hadoop2.7.tgz
RUN cd /usr/local && ln -s ./spark-2.3.0-bin-hadoop2.7 /usr/local/spark
ENV PATH $PATH:/usr/local/spark/bin

# Avro 1.8.2
RUN curl -v -j -k -L -O 'http://apache.claz.org/avro/avro-1.8.2/py3/avro-python3-1.8.2.tar.gz'
RUN tar -xzf avro-python3-1.8.2.tar.gz
RUN cp -R avro-python3-1.8.2 /usr/local
RUN rm -rf avro-python3-1.8.2
RUN rm -f avro-python3-1.8.2.tar.gz
RUN cd usr.local && ln -s ./avro-python3-1.8.2 /usr/local/avro
RUN cd /usr/local/avro && python3.6 setup.py install

RUN mkdir /root/scripts
COPY ./docker/entrypoint-jobs.sh /root/scripts/entrypoint.sh
RUN chmod +x /root/scripts/entrypoint.sh

RUN mkdir /root/nbaTrends
RUN mkdir /root/nbaTrends/src
ADD ./src /root/nbaTrends/src
ADD ./requirements.txt /root/nbaTrends
RUN ln -sfn /usr/bin/python3.6 /usr/bin/python
RUN pip3.6 install -r /root/nbaTrends/requirements.txt

# filebeat
ADD ./docker/filebeat-jobs.yml /usr/share/filebeat/filebeat.yml
RUN chown root:filebeat /usr/share/filebeat/filebeat.yml

WORKDIR /root/nbaTrends

# spark ports
EXPOSE 8080 7077

ENTRYPOINT ["/root/scripts/entrypoint.sh"]